#!/bin/sh
# Author: Yunpeng Li
unset GREP_OPTIONS

# 读取commit log
MSG="$1"
COMMIT_MSG=`cat "$MSG"`
# 去掉以#开头的注释
COMMIT_MSG=`echo "$COMMIT_MSG" | grep -v "^#"`

formatPattern='^【((功能)|(更新)|(Merge)|(提测)|(FixBug)|(商店))】【[0-9](.[0-9])+】.*'
urlPattern='(https?)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'

if [[ !($COMMIT_MSG =~ $formatPattern) ]];then
	echo "你当前填写的Commit Log不合法"
	if [[ $COMMIT_MSG == "" ]];then
		echo "你没有填写任何Commit Log"
	else
		echo "你当前填写的Commit Log为:"
		echo "$COMMIT_MSG"
	fi
	echo ""
	echo "Commit Log格式为："
	echo "    【类型】【预计上线版本号】XXXXXX"
	echo "类型分为："
	echo "    【功能】【更新】【Merge】【提测】【FixBug】【商店】"
	echo "示例："
	echo "    【更新】【3.0.0】完善表白详情页面，添加评论列表"
	echo ""
	exit 1
fi